In [3]:
pip install numpy

  Using cached numpy-1.26.0-cp311-cp311-win_amd64.whl (15.8 MB)
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np
np.ones(100)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
import numpy as np
np.ones(100,dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [6]:
import numpy as np
a=np.array([1,2,3])
b=np.array([(1.2,45,22,4),(4,2,5,6)],dtype=str)
print(a)
print(b)

[1 2 3]
[['1.2' '45' '22' '4']
 ['4' '2' '5' '6']]


INITIAL PLACEHOLDERS


In [48]:
import numpy as np
np.zeros((3,4))
np.ones((2,3,4),dtype=np.int16)
d=np.arange(10,30,5)
np.linspace(0,2,9)
a=np.full((7,5),77)
b=np.eye(3)
c=np.random.random((2))
np.empty((3,3))

#Create an array of zeros
#Create an array of ones
#Create an array of evenly spaced values(step value)
#Create an array of evenly spaced values(number of samples)
#Create a constant array
#Create a 2X2 identity matrix
# #Create an array with random values
# #Create an empty array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

SAVING AND LOADING AN ARRAY

In [61]:
import numpy as np
a=np.array([(3,4,5,6),(2,6,4,8)])
np.save('my_array',a)   #To save an array
np.load('my_array.npy')   #To load an array


array([[3, 4, 5, 6],
       [2, 6, 4, 8]])

In [8]:
import numpy as np
list=[[1,2,3,4,5,6,7],[1,5,4,9,8,7,2]]
array1=np.array(list)
print(array1)
c=0
for i in array1:
    c=np.reshape(3,4)
    print(c)


[[1 2 3 4 5 6 7]
 [1 5 4 9 8 7 2]]


ValueError: cannot reshape array of size 1 into shape (4,)